### ISSUE TITLE
Failed to activate the atom-matlab-editor package

### ISSUE THREAD

**Issue by Geudiel1988** [elpollodiablo84/atom-matlab-editor#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [atom-matlab-editor](https://github.com/elpollodiablo84/atom-matlab-editor) package 0.5.0

### Stack Trace

Failed to activate the atom-matlab-editor package

```
At Invalid filename

Error: Invalid filename
    at /packages/atom-matlab-editor/node_modules/adm-zip/adm-zip.js:22:10)
    at Object.updateCurrentFolderStatusbar (/packages/atom-matlab-editor/lib/atom-matlab-editor.js:565:23)
    at Object.activate (/packages/atom-matlab-editor/lib/atom-matlab-editor.js:197:20)
    at Package.activateNow (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699687)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699099
    at Package.measure (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3696677)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3698959
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3698902)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:383522)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:383138
    at Config.transactAsync (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:332691)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:383088)
    at PackageManager.activate (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:382638)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:758672
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:759157)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify undefined 
atom-css-clean 2.24.1 
atom-formatter-jsbeautify 1.1.2 
atom-ide-ui 0.13.0 
atom-language-matlab 0.4.0 
atom-live-server 2.3.0 
atom-math 0.0.9 
atom-matlab-editor 0.5.0 
atom-sass 0.4.0 
atom-ternjs 0.20.0 
atom-typescript 14.1.2 
autocomplete 0.47.0 
autocomplete-java 1.2.7 
autocomplete-javascript 0.0.2 
autocomplete-json 5.5.4 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.15 
autocomplete-sql 0.5.0 
autosave-onchange 1.5.1 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
bracket-colorizer 1.4.0 
color-tabs 0.1.8 
colorpicker 0.3.0 
comment 0.6.1 
convert-html-to-js 1.0.3 
css-color-name 0.4.0 
css-from-html 0.1.5 
css-grid-snippets 1.1.1 
css-helper-snippets 0.3.0 
css-in-js 1.4.0 
css-snippets 1.1.0 
docblock-format-helper 0.3.0 
docblockr 0.13.7 
editorconfig 2.6.1 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-snippets-compatibility 1.0.6 
es6-javascript 1.0.0 
es6-snippets 0.3.0 
file-icons 2.1.46 
goto-definition 1.3.4 
highlight-colors 0.9.0 
highlight-selected 0.17.0 
html-head-snippets 0.2.0 
html-tag-auto-complete 2.0.0 
html-template-generator 0.3.0 
html-to-css 0.2.2 
html-to-javascript 0.2.0 
html-to-less 1.2.2 
html-wrapper 0.2.0 
hyperclick 0.0.0 
hyphperclick 0.0.2 
ide-css 0.3.5 
ide-html 0.6.2 
ide-json 0.2.1 
ide-php 0.7.18 
ide-typescript 0.9.1 
javascript-refactor 0.7.1 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-blade 0.46.0 
language-javascript-jsx 0.3.7 
language-matlab 0.2.1 
linter 3.1.1 
linter-sass-lint 1.9.0 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
materialize-css 0.5.1 
minimap 4.36.13 
pigments 0.40.6 
Quick-JavaScript 2.2.0 
sass 0.5.0 
section-comment-snippets 2.4.1 
turbo-javascript 1.4.0 
vk-terminal 3.0.1 
```

**Comment by elpollodiablo84** [comment]
Could you provide your Matlab Version? In case you have a version older than R2020a, please check the relative option in the pacjkage's settings.

**Comment by diegoomataix** [comment]
Hello @elpollodiablo84, I am also having the same issue using R2020b. Thanks

**Comment by elpollodiablo84** [comment]
Ok, the problem is that the package can't find the `matlab.mlsettings` file (I'm assuming @Geudiel1988 is using a newer version like @diegoomataix). This is strange, since I thought that starting with R2020a Mathworks switched to using that file instead of the old `matlab.settings`.
I don't have access to Matlab R2020b, so I would like to ask you to:
1. be sure that all the package settings are properly set, specifically all the MATLAB folders
2. check the content of the MATLAB `prefdir`: is there any file called `matlab.some_extension`? What are their extensions? And in case you have/had multiple version of Matlab installed, what is currently used (check the "Last modified" property?

Meanwhile I will work on a more robust handling of these files.
Thank you for your help!

**Comment by elpollodiablo84** [comment]
The new release (0.5.1) should resolve this issue. In case you still can't see the MATLAB current directory in Atom, let me know.
